spring:
  security:
    user:
      password: changeMe
  session:
    store-type: redis
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
      sensitive-headers:
